### ISSUE TITLE
WhoV2AuthenticationPolicy.remember() 'identifier'  set incorrectly?

### ISSUE THREAD

**Issue by ghost** [Pylons/pyramid_who#2]
Could be a configuration error, but 
identity = {'identifier' : self._identifier_id }
results in this error: 
'auth_tkt'.remember()

This works:
identity = {'identifier': api.name_registry.get(self._identifier_id) }

**Comment by tseaver** [comment]
Thank you for the report.  I have checked in a fix which addresses it:

 0d509e7c87559628afd5bc36402751319b16d3e4

**Comment by tseaver** [comment]
Fix released w/ pyramid_who 0.2:

 http://pypi.python.org/pypi/pyramid_who/0.2
